In [2]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('datasets/dirty_customers.csv')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      30 non-null     int64
 1   name             30 non-null     str
 2   age              28 non-null     str
 3   gender           30 non-null     str
 4   city             28 non-null     str
 5   email            28 non-null     str
 6   phone            30 non-null     str
 7   signup_date      30 non-null     str
 8   purchase_amount  28 non-null     str
 9   category         30 non-null     str
dtypes: int64(1), str(9)
memory usage: 2.5 KB

In [ ]:
print(df.to_string())
# to_string prints all of the data

    customer_id             name     age  gender      city              email          phone signup_date purchase_amount     category
0          1001       John Kamau      24    Male   Nairobi     john@gmail.com   0712-345-678  2025-01-15         4500.50  Electronics
1          1002    Mary Wanjiku       29  Female   nairobi     mary@gmail.com   0722 456 789  15/01/2025            3200     Clothing
2          1003     PETER OTIENO      34       M    Kisumu    peter@gmail.com  +254733123456  2025/02/03         1250.75  electronics
3          1004        Ann Njeri     NaN  Female       NaN      ann@gmail.com   0700-111-222  03-02-2025             850     Clothing
4          1005     Brian Mwangi      17    Male    Nakuru        brian@gmail     0712345678  2025-02-10         1200.00         Food
5          1006      Jane Wambui      31  Female   Nairobi                NaN   0722-999-888  2025-02-11         3400.50  Electronics
6          1007    david kariuki      45    male   Nairobi    david@gmail.com   0733 555 444  11/02/2025            5000  electronics
7          1008     Susan Akinyi      28  Female   Mombasa    susan@gmail.com   0701-222-333  2025-02-15             NaN     Clothing
8          1009     Kevin Otieno      -5    Male    Kisumu    kevin@gmail.com   0711-333-444  2025-02-16            2200         Food
9          1010     Lucy Wairimu     150       F   Nairobi     lucy@gmail.com   0722-111-999  2025-02-18         1800.25         food
10         1011       Mark Mutua      26    Male     Thika     mark@gmail.com   0700 123 456  2025-02-20            2700  Electronics
11         1012     Grace Chebet      33  Female   Eldoret    grace@gmail.com   0712-777-888  20/02/2025         3100.75     Clothing
12         1013  Samuel Kiplagat      27    Male   Eldoret   samuel@gmail.com     0712777888  2025-02-21            4500         Food
13         1014      Jane Wambui      31  Female   Nairobi                NaN   0722-999-888  2025-02-11         3400.50  Electronics
14         1015     Mary Wanjiku      29  female   nairobi     mary@gmail.com   0722 456 789  2025-01-15           3,200     clothing
15         1016     Peter Otieno      34       M    KISUMU    peter@gmail.com  +254733123456  2025-02-03         1250.75  Electronics
16         1017      Daniel Ouma      22    Male   Nairobi   daniel@gmail.com   0700-444-555  2025-02-25            1500         FOOD
17         1018     Faith Atieno      25  Female   Mombasa    faith@gmail.com   0711-555-666  2025-02-26        2,750.50     Clothing
18         1019     George Maina  thirty    Male    Kiambu   george@gmail.com   0722-666-777  2025-02-28            1900  Electronics
19         1020   Carol Nyambura      23  Female    Kiambu    carol@gmail.com   0733-888-999  2025-02-30            2100         Food
20         1021   Joseph Kariuki      36    Male     Thika   joseph@gmail.com     0700111222  2025-03-01         3200.00  Electronics
21         1022    Esther Wambui      30  Female   Nairobi   esther@gmail.com   0712-222-333  01/03/2025            2800     Clothing
22         1023  Michael Onyango      41    Male    Kisumu  michael@gmail.com   0733-111-222  2025-03-03            4500  Electronics
23         1024    Agnes Wanjiru      27  Female    Nakuru    agnes@gmail.com   0701 333 444  03/03/2025            1750         Food
24         1025       John Kamau      24    Male   Nairobi     john@gmail.com   0712-345-678  2025-01-15         4500.50  Electronics
25         1026     Peter Otieno      34    Male    Kisumu    peter@gmail.com   0712-123-456  2025-03-05         1250.75   Electronic
26         1027     Rose Naliaka     NaN  Female  Kakamega     rose@gmail.com   0722-333-444  2025-03-06             900     Clothing
27         1028     Patrick Were      39    Male       NaN  patrick@gmail.com   0700-555-666  2025-03-07            3800         Food
28         1029  Emily Chepkirui      26  Female   Eldoret    emily@gmail.com   0711-777-888  2025-03-08             NaN     Clothing
29         1030   Anthony Mwangi      32    Male     Thika  anthony@gmail.com   0733-999-000  2025-03-09         4200.00  Electronics

In [ ]:
df['customer_id'].unique()

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
       1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
       1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030])

## Workflow
#### 1. import pandas
#### 2. load the dataset
#### 3.General information about the dataset
#### 4. Check to see general values in the dataset
#### 5. Information per column
#### 6. How to clean it

In [ ]:
df.dtypes.unique()

array([dtype('int64'), <StringDtype(storage='python', na_value=nan)>],
      dtype=object)

In [ ]:
df['name'].unique()
df['name']= df['name'].str.strip()
df['name']= df['name'].str.capitalize()
df['name'].unique()

<StringArray>
[     'John kamau',    'Mary wanjiku',    'Peter otieno',       'Ann njeri',
    'Brian mwangi',     'Jane wambui',   'David kariuki',    'Susan akinyi',
    'Kevin otieno',    'Lucy wairimu',      'Mark mutua',    'Grace chebet',
 'Samuel kiplagat',     'Daniel ouma',    'Faith atieno',    'George maina',
  'Carol nyambura',  'Joseph kariuki',   'Esther wambui', 'Michael onyango',
   'Agnes wanjiru',    'Rose naliaka',    'Patrick were', 'Emily chepkirui',
  'Anthony mwangi']
Length: 25, dtype: str

In [ ]:
df['age'].value_counts()
df['age']=pd.to_numeric(df['age'],errors='coerce')
df.loc[(df['age']<0) | (df['age']>100)]=np.nan
df.dropna(inplace=True)
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,nairobi,mary@gmail.com,0722 456 789,15/01/2025,3200,Clothing
2,1003.0,Peter otieno,34.0,M,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,brian@gmail,0712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,male,Nairobi,david@gmail.com,0733 555 444,11/02/2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,0700 123 456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,0712-777-888,20/02/2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,female,nairobi,mary@gmail.com,0722 456 789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,M,KISUMU,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,0700-444-555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,0711-555-666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,0733-888-999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,0712-222-333,01/03/2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,0733-111-222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,0701 333 444,03/03/2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,0712-123-456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,0733-999-000,2025-03-09,4200.00,Electronics

In [ ]:

df['gender']= df['gender'].str.strip()
df['gender']= df['gender'].str.capitalize()
df['gender'].unique()

<StringArray>
['Male', 'Female', 'M']
Length: 3, dtype: str

In [ ]:
df['gender']=df['gender'].replace({
    "M":"Male"
})
df['gender'].value_counts()

gender
Male      13
Female     7
Name: count, dtype: int64

In [ ]:
df['city']=df['city'].str.strip().str.capitalize()
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722 456 789,15/01/2025,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,brian@gmail,0712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,0733 555 444,11/02/2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,0700 123 456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,0712-777-888,20/02/2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722 456 789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,0700-444-555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,0711-555-666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,0733-888-999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,0712-222-333,01/03/2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,0733-111-222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,0701 333 444,03/03/2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,0712-123-456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,0733-999-000,2025-03-09,4200.00,Electronics

In [ ]:
email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"
valid_email=df['email'].str.match(email_pattern, na=False)
print(valid_email)
df.loc[~valid_email,'email']=pd.NA

0      True
1      True
2      True
4     False
6      True
10     True
11     True
12     True
14     True
15     True
16     True
17     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
29     True
Name: email, dtype: bool

In [ ]:
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722 456 789,15/01/2025,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,0712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,0733 555 444,11/02/2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,0700 123 456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,0712-777-888,20/02/2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722 456 789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,0700-444-555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,0711-555-666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,0733-888-999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,0712-222-333,01/03/2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,0733-111-222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,0701 333 444,03/03/2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,0712-123-456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,0733-999-000,2025-03-09,4200.00,Electronics

In [ ]:
df['phone']=df['phone'].str.replace('-','').str.replace(' ','')
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722456789,15/01/2025,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,0712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,0733555444,11/02/2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,0700123456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,0712777888,20/02/2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,0722456789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,0700444555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,0711555666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,0733888999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,0712222333,01/03/2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,0733111222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,0701333444,03/03/2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,0712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,0712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,0733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['phone']=df['phone'].str.replace(r"^07","+2547",regex=True)
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,15/01/2025,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,11/02/2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,20/02/2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,01/03/2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,03/03/2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['signup_date']=df['signup_date'].str.replace('/', '-', regex=False)
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,15-01-2025,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,11-02-2025,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,20-02-2025,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,2025-02-30,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,01-03-2025,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,03-03-2025,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['signup_date']=df['signup_date'].apply(lambda x:pd.to_datetime(x,errors='coerce'))
df

/tmp/ipykernel_460876/334242108.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['signup_date']=df['signup_date'].apply(lambda x:pd.to_datetime(x,errors='coerce'))

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,2025-11-02,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,2025-02-20,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,"3,200",clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,"2,750.50",Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,NaT,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,2025-01-03,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,2025-03-03,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['purchase_amount']=df['purchase_amount'].astype(str).str.replace(',', '').str.strip()
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,2025-11-02,5000,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,2025-02-20,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200,clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,2750.50,Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,NaT,2100,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,2025-01-03,2800,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,2025-03-03,1750,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['purchase_amount']=pd.to_numeric(df['purchase_amount'], errors='coerce')
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200.00,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,2025-11-02,5000.00,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700.00,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,2025-02-20,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500.00,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200.00,clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500.00,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,2750.50,Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,NaT,2100.00,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,2025-01-03,2800.00,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500.00,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,2025-03-03,1750.00,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [ ]:
df['purchase_amount']=df['purchase_amount'].fillna(0)
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
1,1002.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200.00,Clothing
2,1003.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
4,1005.0,Brian mwangi,17.0,Male,Nakuru,NaN,+254712345678,2025-02-10,1200.00,Food
6,1007.0,David kariuki,45.0,Male,Nairobi,david@gmail.com,+254733555444,2025-11-02,5000.00,electronics
10,1011.0,Mark mutua,26.0,Male,Thika,mark@gmail.com,+254700123456,2025-02-20,2700.00,Electronics
11,1012.0,Grace chebet,33.0,Female,Eldoret,grace@gmail.com,+254712777888,2025-02-20,3100.75,Clothing
12,1013.0,Samuel kiplagat,27.0,Male,Eldoret,samuel@gmail.com,+254712777888,2025-02-21,4500.00,Food
14,1015.0,Mary wanjiku,29.0,Female,Nairobi,mary@gmail.com,+254722456789,2025-01-15,3200.00,clothing
15,1016.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254733123456,2025-02-03,1250.75,Electronics
16,1017.0,Daniel ouma,22.0,Male,Nairobi,daniel@gmail.com,+254700444555,2025-02-25,1500.00,FOOD
17,1018.0,Faith atieno,25.0,Female,Mombasa,faith@gmail.com,+254711555666,2025-02-26,2750.50,Clothing
19,1020.0,Carol nyambura,23.0,Female,Kiambu,carol@gmail.com,+254733888999,NaT,2100.00,Food
20,1021.0,Joseph kariuki,36.0,Male,Thika,joseph@gmail.com,+254700111222,2025-03-01,3200.00,Electronics
21,1022.0,Esther wambui,30.0,Female,Nairobi,esther@gmail.com,+254712222333,2025-01-03,2800.00,Clothing
22,1023.0,Michael onyango,41.0,Male,Kisumu,michael@gmail.com,+254733111222,2025-03-03,4500.00,Electronics
23,1024.0,Agnes wanjiru,27.0,Female,Nakuru,agnes@gmail.com,+254701333444,2025-03-03,1750.00,Food
24,1025.0,John kamau,24.0,Male,Nairobi,john@gmail.com,+254712345678,2025-01-15,4500.50,Electronics
25,1026.0,Peter otieno,34.0,Male,Kisumu,peter@gmail.com,+254712123456,2025-03-05,1250.75,Electronic
29,1030.0,Anthony mwangi,32.0,Male,Thika,anthony@gmail.com,+254733999000,2025-03-09,4200.00,Electronics

In [8]:
df['category']=df['category'].astype(str).str.lower().str.strip()
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001,John Kamau,24,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,electronics
1,1002,Mary Wanjiku,29,Female,nairobi,mary@gmail.com,0722 456 789,15/01/2025,3200,clothing
2,1003,PETER OTIENO,34,M,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
3,1004,Ann Njeri,NaN,Female,NaN,ann@gmail.com,0700-111-222,03-02-2025,850,clothing
4,1005,Brian Mwangi,17,Male,Nakuru,brian@gmail,0712345678,2025-02-10,1200.00,food
5,1006,Jane Wambui,31,Female,Nairobi,NaN,0722-999-888,2025-02-11,3400.50,electronics
6,1007,david kariuki,45,male,Nairobi,david@gmail.com,0733 555 444,11/02/2025,5000,electronics
7,1008,Susan Akinyi,28,Female,Mombasa,susan@gmail.com,0701-222-333,2025-02-15,NaN,clothing
8,1009,Kevin Otieno,-5,Male,Kisumu,kevin@gmail.com,0711-333-444,2025-02-16,2200,food
9,1010,Lucy Wairimu,150,F,Nairobi,lucy@gmail.com,0722-111-999,2025-02-18,1800.25,food
10,1011,Mark Mutua,26,Male,Thika,mark@gmail.com,0700 123 456,2025-02-20,2700,electronics
11,1012,Grace Chebet,33,Female,Eldoret,grace@gmail.com,0712-777-888,20/02/2025,3100.75,clothing
12,1013,Samuel Kiplagat,27,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,food
13,1014,Jane Wambui,31,Female,Nairobi,NaN,0722-999-888,2025-02-11,3400.50,electronics
14,1015,Mary Wanjiku,29,female,nairobi,mary@gmail.com,0722 456 789,2025-01-15,"3,200",clothing
15,1016,Peter Otieno,34,M,KISUMU,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
16,1017,Daniel Ouma,22,Male,Nairobi,daniel@gmail.com,0700-444-555,2025-02-25,1500,food
17,1018,Faith Atieno,25,Female,Mombasa,faith@gmail.com,0711-555-666,2025-02-26,"2,750.50",clothing
18,1019,George Maina,thirty,Male,Kiambu,george@gmail.com,0722-666-777,2025-02-28,1900,electronics
19,1020,Carol Nyambura,23,Female,Kiambu,carol@gmail.com,0733-888-999,2025-02-30,2100,food
20,1021,Joseph Kariuki,36,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,electronics
21,1022,Esther Wambui,30,Female,Nairobi,esther@gmail.com,0712-222-333,01/03/2025,2800,clothing
22,1023,Michael Onyango,41,Male,Kisumu,michael@gmail.com,0733-111-222,2025-03-03,4500,electronics
23,1024,Agnes Wanjiru,27,Female,Nakuru,agnes@gmail.com,0701 333 444,03/03/2025,1750,food
24,1025,John Kamau,24,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,electronics
25,1026,Peter Otieno,34,Male,Kisumu,peter@gmail.com,0712-123-456,2025-03-05,1250.75,electronic
26,1027,Rose Naliaka,NaN,Female,Kakamega,rose@gmail.com,0722-333-444,2025-03-06,900,clothing
27,1028,Patrick Were,39,Male,NaN,patrick@gmail.com,0700-555-666,2025-03-07,3800,food
28,1029,Emily Chepkirui,26,Female,Eldoret,emily@gmail.com,0711-777-888,2025-03-08,NaN,clothing
29,1030,Anthony Mwangi,32,Male,Thika,anthony@gmail.com,0733-999-000,2025-03-09,4200.00,electronics

In [10]:
df['category'].value_counts()

category
electronics    12
clothing        9
food            8
electronic      1
Name: count, dtype: int64

In [11]:
df['category'].isnull().sum()
df

,customer_id,name,age,gender,city,email,phone,signup_date,purchase_amount,category
0,1001,John Kamau,24,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,electronics
1,1002,Mary Wanjiku,29,Female,nairobi,mary@gmail.com,0722 456 789,15/01/2025,3200,clothing
2,1003,PETER OTIENO,34,M,Kisumu,peter@gmail.com,+254733123456,2025/02/03,1250.75,electronics
3,1004,Ann Njeri,NaN,Female,NaN,ann@gmail.com,0700-111-222,03-02-2025,850,clothing
4,1005,Brian Mwangi,17,Male,Nakuru,brian@gmail,0712345678,2025-02-10,1200.00,food
5,1006,Jane Wambui,31,Female,Nairobi,NaN,0722-999-888,2025-02-11,3400.50,electronics
6,1007,david kariuki,45,male,Nairobi,david@gmail.com,0733 555 444,11/02/2025,5000,electronics
7,1008,Susan Akinyi,28,Female,Mombasa,susan@gmail.com,0701-222-333,2025-02-15,NaN,clothing
8,1009,Kevin Otieno,-5,Male,Kisumu,kevin@gmail.com,0711-333-444,2025-02-16,2200,food
9,1010,Lucy Wairimu,150,F,Nairobi,lucy@gmail.com,0722-111-999,2025-02-18,1800.25,food
10,1011,Mark Mutua,26,Male,Thika,mark@gmail.com,0700 123 456,2025-02-20,2700,electronics
11,1012,Grace Chebet,33,Female,Eldoret,grace@gmail.com,0712-777-888,20/02/2025,3100.75,clothing
12,1013,Samuel Kiplagat,27,Male,Eldoret,samuel@gmail.com,0712777888,2025-02-21,4500,food
13,1014,Jane Wambui,31,Female,Nairobi,NaN,0722-999-888,2025-02-11,3400.50,electronics
14,1015,Mary Wanjiku,29,female,nairobi,mary@gmail.com,0722 456 789,2025-01-15,"3,200",clothing
15,1016,Peter Otieno,34,M,KISUMU,peter@gmail.com,+254733123456,2025-02-03,1250.75,electronics
16,1017,Daniel Ouma,22,Male,Nairobi,daniel@gmail.com,0700-444-555,2025-02-25,1500,food
17,1018,Faith Atieno,25,Female,Mombasa,faith@gmail.com,0711-555-666,2025-02-26,"2,750.50",clothing
18,1019,George Maina,thirty,Male,Kiambu,george@gmail.com,0722-666-777,2025-02-28,1900,electronics
19,1020,Carol Nyambura,23,Female,Kiambu,carol@gmail.com,0733-888-999,2025-02-30,2100,food
20,1021,Joseph Kariuki,36,Male,Thika,joseph@gmail.com,0700111222,2025-03-01,3200.00,electronics
21,1022,Esther Wambui,30,Female,Nairobi,esther@gmail.com,0712-222-333,01/03/2025,2800,clothing
22,1023,Michael Onyango,41,Male,Kisumu,michael@gmail.com,0733-111-222,2025-03-03,4500,electronics
23,1024,Agnes Wanjiru,27,Female,Nakuru,agnes@gmail.com,0701 333 444,03/03/2025,1750,food
24,1025,John Kamau,24,Male,Nairobi,john@gmail.com,0712-345-678,2025-01-15,4500.50,electronics
25,1026,Peter Otieno,34,Male,Kisumu,peter@gmail.com,0712-123-456,2025-03-05,1250.75,electronic
26,1027,Rose Naliaka,NaN,Female,Kakamega,rose@gmail.com,0722-333-444,2025-03-06,900,clothing
27,1028,Patrick Were,39,Male,NaN,patrick@gmail.com,0700-555-666,2025-03-07,3800,food
28,1029,Emily Chepkirui,26,Female,Eldoret,emily@gmail.com,0711-777-888,2025-03-08,NaN,clothing
29,1030,Anthony Mwangi,32,Male,Thika,anthony@gmail.com,0733-999-000,2025-03-09,4200.00,electronics