In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('dirty_students.csv')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student_ID       50 non-null     str
 1   Name             49 non-null     str
 2   Age              50 non-null     str
 3   Gender           50 non-null     str
 4   Study_Hours      48 non-null     float64
 5   Attendance       49 non-null     str
 6   Previous_Score   50 non-null     int64
 7   Internet_Access  50 non-null     str
 8   Part_Time_Job    49 non-null     str
 9   Performance      50 non-null     str
dtypes: float64(1), int64(1), str(8)
memory usage: 4.0 KB

In [9]:
print(df.to_string())

   Student_ID               Name     Age  Gender  Study_Hours Attendance  Previous_Score Internet_Access Part_Time_Job Performance
0      STU001        John Mwangi      20    Male         15.0        85%              72             Yes            No        Good
1      STU002       Jane Wanjiku      21  Female         22.0        91%              81             Yes            No   Excellent
2      STU003        Peter Kamau      19       M         10.0        78%              65             YES            No     Average
3      STU004        mary njeri       22       F         18.0        88%              74             Yes           YES        Good
4      STU005      David Ochieng  twenty    Male         25.0        95%              89             Yes            No   Excellent
5      STU006       Grace Akinyi      20  Female          NaN        82%              68              No           Yes     Average
6      STU007       Brian Otieno      21    Male         30.0       110%              92             Yes            No   Excellent
7      STU008       Susan Wambui      19  Female          8.0        75%              54              No            No        poor
8      STU009      Kevin Kariuki      23       M         12.0        80%              61             yes            No     Average
9      STU010       Ann Nyambura      20  Female         20.0        87%              76             Yes            No        Good
10     STU011      Samuel Kiptoo      21    Male         -5.0        89%              70             Yes           Yes        Good
11     STU012      Lilian Chebet      22  Female         16.0        NaN              84             Yes            No   Excellent
12     STU013        James Maina      19    Male         14.0        83%              59              No           Yes     Average
13     STU014      Faith Wairimu      20  Female         21.0        92%              88             Yes            No   Excellent
14     STU015      Michael Kibet      25    Male         40.0        97%              95             Yes            No   Excellent
15     STU016        Lucy Atieno      19       F         11.0        76%              62              NO            No     Average
16     STU017       Daniel Mutua      21    Male          NaN        84%              71             Yes            No        Good
17     STU018       Carol Wambui      20  Female         19.0        89%              79             Yes           Yes        Good
18     STU019        Eric Omondi      22    Male         17.0        81%              67             Yes            No     average
19     STU020      Beatrice Auma      19  Female         13.0        73%              55              No           Yes        Poor
20     STU021        John Mwangi      20    Male         15.0        85%              72             Yes            No        Good
21     STU022        Peter Kamau      19       M         10.0        78%              65             YES            No     Average
22     STU023         Rose Njeri     abc  Female         18.0        88%              74             Yes            No        Good
23     STU024     Joseph Kariuki      21    Male        100.0        90%              82             Yes            No   Excellent
24     STU025      Agnes Wanjiku      20  Female         23.0       105%              91             Yes            No   Excellent
25     STU026                NaN      22    Male         16.0        86%              73             Yes            No        Good
26     STU027       Patrick Ouma      19    Male          9.0        79%              60              No           Yes     Average
27     STU028       Sarah Chebet      21  Female         18.0        88%              77             Yes            No        Good
28     STU029        Mark Otieno      20    Male         15.0        82%              69             Yes           NaN     Average
29     STU030      Alice Wanjiru      19       F         12.0        74%              58              No            No        Poor
30     STU031       Victor Maina      20    Male         20.0        90%              80             Yes            No        Good
31     STU032   Elizabeth Akinyi      21  Female         24.0        93%              87             Yes            No   Excellent
32     STU033       George Mutua      22    Male         17.0        85%              75             Yes           Yes        Good
33     STU034  Christine Wairimu      20  Female         14.0        80%              64              No            No     Average
34     STU035      Robert Kiptoo      19    male         16.0        83%              70             Yes            No        Good
35     STU036       Naomi Chebet      21  FEMALE         19.0        91%              85             Yes            No   Excellent
36     STU037     Samuel Ochieng      20    Male         13.0        78%              63              No           Yes     Average
37     STU038        Mercy Auma       19  Female         10.0        72%              51              No           Yes        poor
38     STU039        David Kamau      21    Male         18.0        86%              78             Yes            No        Good
39     STU040        Jane Wambui      20  Female         21.0        94%              90             Yes            No   Excellent
40     STU041      Kevin Kariuki      23       M         12.0        80%              61             yes            No     Average
41     STU042       Brian Otieno      21    Male         30.0        89%              92             Yes            No   Excellent
42     STU043        Lucy Atieno      19  Female         11.0        76%              62              NO            No     Average
43     STU044       Daniel Mutua      21    Male         17.0        84%              71             Yes            No        Good
44     STU045      Faith Wairimu      20  Female         21.0        92%              88             Yes            No   Excellent
45     STU046      Michael Kibet      25    Male         40.0        97%              95             Yes            No   Excellent
46     STU047       Carol Wambui      20  Female         19.0        89%              79             Yes           Yes        Good
47     STU048        Eric Omondi      22    Male         17.0        81%              67             Yes            No     average
48     STU049      Beatrice Auma      19  Female         13.0        73%              55              No           Yes        Poor
49     STU050     Joseph Kariuki      21    Male         15.0        88%              82             Yes            No        Good

In [ ]:
import pandas as pd 
import numpy as np

In [13]:
df['Age']=pd.to_numeric(df['Age'], errors='coerce')
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20.0,Male,15.0,85%,72,Yes,No,Good
1,STU002,Jane Wanjiku,21.0,Female,22.0,91%,81,Yes,No,Excellent
2,STU003,Peter Kamau,19.0,M,10.0,78%,65,YES,No,Average
3,STU004,mary njeri,22.0,F,18.0,88%,74,Yes,YES,Good
4,STU005,David Ochieng,NaN,Male,25.0,95%,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20.0,Female,NaN,82%,68,No,Yes,Average
6,STU007,Brian Otieno,21.0,Male,30.0,110%,92,Yes,No,Excellent
7,STU008,Susan Wambui,19.0,Female,8.0,75%,54,No,No,poor
8,STU009,Kevin Kariuki,23.0,M,12.0,80%,61,yes,No,Average
9,STU010,Ann Nyambura,20.0,Female,20.0,87%,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21.0,Male,-5.0,89%,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22.0,Female,16.0,NaN,84,Yes,No,Excellent
12,STU013,James Maina,19.0,Male,14.0,83%,59,No,Yes,Average
13,STU014,Faith Wairimu,20.0,Female,21.0,92%,88,Yes,No,Excellent
14,STU015,Michael Kibet,25.0,Male,40.0,97%,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19.0,F,11.0,76%,62,NO,No,Average
16,STU017,Daniel Mutua,21.0,Male,NaN,84%,71,Yes,No,Good
17,STU018,Carol Wambui,20.0,Female,19.0,89%,79,Yes,Yes,Good
18,STU019,Eric Omondi,22.0,Male,17.0,81%,67,Yes,No,average
19,STU020,Beatrice Auma,19.0,Female,13.0,73%,55,No,Yes,Poor
20,STU021,John Mwangi,20.0,Male,15.0,85%,72,Yes,No,Good
21,STU022,Peter Kamau,19.0,M,10.0,78%,65,YES,No,Average
22,STU023,Rose Njeri,NaN,Female,18.0,88%,74,Yes,No,Good
23,STU024,Joseph Kariuki,21.0,Male,100.0,90%,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20.0,Female,23.0,105%,91,Yes,No,Excellent
25,STU026,NaN,22.0,Male,16.0,86%,73,Yes,No,Good
26,STU027,Patrick Ouma,19.0,Male,9.0,79%,60,No,Yes,Average
27,STU028,Sarah Chebet,21.0,Female,18.0,88%,77,Yes,No,Good
28,STU029,Mark Otieno,20.0,Male,15.0,82%,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19.0,F,12.0,74%,58,No,No,Poor
30,STU031,Victor Maina,20.0,Male,20.0,90%,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21.0,Female,24.0,93%,87,Yes,No,Excellent
32,STU033,George Mutua,22.0,Male,17.0,85%,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20.0,Female,14.0,80%,64,No,No,Average
34,STU035,Robert Kiptoo,19.0,male,16.0,83%,70,Yes,No,Good
35,STU036,Naomi Chebet,21.0,FEMALE,19.0,91%,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20.0,Male,13.0,78%,63,No,Yes,Average
37,STU038,Mercy Auma,19.0,Female,10.0,72%,51,No,Yes,poor
38,STU039,David Kamau,21.0,Male,18.0,86%,78,Yes,No,Good
39,STU040,Jane Wambui,20.0,Female,21.0,94%,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23.0,M,12.0,80%,61,yes,No,Average
41,STU042,Brian Otieno,21.0,Male,30.0,89%,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19.0,Female,11.0,76%,62,NO,No,Average
43,STU044,Daniel Mutua,21.0,Male,17.0,84%,71,Yes,No,Good
44,STU045,Faith Wairimu,20.0,Female,21.0,92%,88,Yes,No,Excellent
45,STU046,Michael Kibet,25.0,Male,40.0,97%,95,Yes,No,Excellent
46,STU047,Carol Wambui,20.0,Female,19.0,89%,79,Yes,Yes,Good
47,STU048,Eric Omondi,22.0,Male,17.0,81%,67,Yes,No,average
48,STU049,Beatrice Auma,19.0,Female,13.0,73%,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21.0,Male,15.0,88%,82,Yes,No,Good

In [17]:
df.loc[df['Age'] < 0, 'Age']= np.nan
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20.0,Male,15.0,85%,72,Yes,No,Good
1,STU002,Jane Wanjiku,21.0,Female,22.0,91%,81,Yes,No,Excellent
2,STU003,Peter Kamau,19.0,M,10.0,78%,65,YES,No,Average
3,STU004,mary njeri,22.0,F,18.0,88%,74,Yes,YES,Good
4,STU005,David Ochieng,NaN,Male,25.0,95%,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20.0,Female,NaN,82%,68,No,Yes,Average
6,STU007,Brian Otieno,21.0,Male,30.0,110%,92,Yes,No,Excellent
7,STU008,Susan Wambui,19.0,Female,8.0,75%,54,No,No,poor
8,STU009,Kevin Kariuki,23.0,M,12.0,80%,61,yes,No,Average
9,STU010,Ann Nyambura,20.0,Female,20.0,87%,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21.0,Male,-5.0,89%,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22.0,Female,16.0,NaN,84,Yes,No,Excellent
12,STU013,James Maina,19.0,Male,14.0,83%,59,No,Yes,Average
13,STU014,Faith Wairimu,20.0,Female,21.0,92%,88,Yes,No,Excellent
14,STU015,Michael Kibet,25.0,Male,40.0,97%,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19.0,F,11.0,76%,62,NO,No,Average
16,STU017,Daniel Mutua,21.0,Male,NaN,84%,71,Yes,No,Good
17,STU018,Carol Wambui,20.0,Female,19.0,89%,79,Yes,Yes,Good
18,STU019,Eric Omondi,22.0,Male,17.0,81%,67,Yes,No,average
19,STU020,Beatrice Auma,19.0,Female,13.0,73%,55,No,Yes,Poor
20,STU021,John Mwangi,20.0,Male,15.0,85%,72,Yes,No,Good
21,STU022,Peter Kamau,19.0,M,10.0,78%,65,YES,No,Average
22,STU023,Rose Njeri,NaN,Female,18.0,88%,74,Yes,No,Good
23,STU024,Joseph Kariuki,21.0,Male,100.0,90%,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20.0,Female,23.0,105%,91,Yes,No,Excellent
25,STU026,NaN,22.0,Male,16.0,86%,73,Yes,No,Good
26,STU027,Patrick Ouma,19.0,Male,9.0,79%,60,No,Yes,Average
27,STU028,Sarah Chebet,21.0,Female,18.0,88%,77,Yes,No,Good
28,STU029,Mark Otieno,20.0,Male,15.0,82%,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19.0,F,12.0,74%,58,No,No,Poor
30,STU031,Victor Maina,20.0,Male,20.0,90%,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21.0,Female,24.0,93%,87,Yes,No,Excellent
32,STU033,George Mutua,22.0,Male,17.0,85%,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20.0,Female,14.0,80%,64,No,No,Average
34,STU035,Robert Kiptoo,19.0,male,16.0,83%,70,Yes,No,Good
35,STU036,Naomi Chebet,21.0,FEMALE,19.0,91%,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20.0,Male,13.0,78%,63,No,Yes,Average
37,STU038,Mercy Auma,19.0,Female,10.0,72%,51,No,Yes,poor
38,STU039,David Kamau,21.0,Male,18.0,86%,78,Yes,No,Good
39,STU040,Jane Wambui,20.0,Female,21.0,94%,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23.0,M,12.0,80%,61,yes,No,Average
41,STU042,Brian Otieno,21.0,Male,30.0,89%,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19.0,Female,11.0,76%,62,NO,No,Average
43,STU044,Daniel Mutua,21.0,Male,17.0,84%,71,Yes,No,Good
44,STU045,Faith Wairimu,20.0,Female,21.0,92%,88,Yes,No,Excellent
45,STU046,Michael Kibet,25.0,Male,40.0,97%,95,Yes,No,Excellent
46,STU047,Carol Wambui,20.0,Female,19.0,89%,79,Yes,Yes,Good
47,STU048,Eric Omondi,22.0,Male,17.0,81%,67,Yes,No,average
48,STU049,Beatrice Auma,19.0,Female,13.0,73%,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21.0,Male,15.0,88%,82,Yes,No,Good

In [19]:
df['Age']= df['Age'].fillna(df['Age'].median()).astype(int)
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
1,STU002,Jane Wanjiku,21,Female,22.0,91%,81,Yes,No,Excellent
2,STU003,Peter Kamau,19,M,10.0,78%,65,YES,No,Average
3,STU004,mary njeri,22,F,18.0,88%,74,Yes,YES,Good
4,STU005,David Ochieng,20,Male,25.0,95%,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20,Female,NaN,82%,68,No,Yes,Average
6,STU007,Brian Otieno,21,Male,30.0,110%,92,Yes,No,Excellent
7,STU008,Susan Wambui,19,Female,8.0,75%,54,No,No,poor
8,STU009,Kevin Kariuki,23,M,12.0,80%,61,yes,No,Average
9,STU010,Ann Nyambura,20,Female,20.0,87%,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21,Male,-5.0,89%,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22,Female,16.0,NaN,84,Yes,No,Excellent
12,STU013,James Maina,19,Male,14.0,83%,59,No,Yes,Average
13,STU014,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
14,STU015,Michael Kibet,25,Male,40.0,97%,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19,F,11.0,76%,62,NO,No,Average
16,STU017,Daniel Mutua,21,Male,NaN,84%,71,Yes,No,Good
17,STU018,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
18,STU019,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
19,STU020,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
20,STU021,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
21,STU022,Peter Kamau,19,M,10.0,78%,65,YES,No,Average
22,STU023,Rose Njeri,20,Female,18.0,88%,74,Yes,No,Good
23,STU024,Joseph Kariuki,21,Male,100.0,90%,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20,Female,23.0,105%,91,Yes,No,Excellent
25,STU026,NaN,22,Male,16.0,86%,73,Yes,No,Good
26,STU027,Patrick Ouma,19,Male,9.0,79%,60,No,Yes,Average
27,STU028,Sarah Chebet,21,Female,18.0,88%,77,Yes,No,Good
28,STU029,Mark Otieno,20,Male,15.0,82%,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19,F,12.0,74%,58,No,No,Poor
30,STU031,Victor Maina,20,Male,20.0,90%,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21,Female,24.0,93%,87,Yes,No,Excellent
32,STU033,George Mutua,22,Male,17.0,85%,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20,Female,14.0,80%,64,No,No,Average
34,STU035,Robert Kiptoo,19,male,16.0,83%,70,Yes,No,Good
35,STU036,Naomi Chebet,21,FEMALE,19.0,91%,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20,Male,13.0,78%,63,No,Yes,Average
37,STU038,Mercy Auma,19,Female,10.0,72%,51,No,Yes,poor
38,STU039,David Kamau,21,Male,18.0,86%,78,Yes,No,Good
39,STU040,Jane Wambui,20,Female,21.0,94%,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23,M,12.0,80%,61,yes,No,Average
41,STU042,Brian Otieno,21,Male,30.0,89%,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19,Female,11.0,76%,62,NO,No,Average
43,STU044,Daniel Mutua,21,Male,17.0,84%,71,Yes,No,Good
44,STU045,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
45,STU046,Michael Kibet,25,Male,40.0,97%,95,Yes,No,Excellent
46,STU047,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
47,STU048,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
48,STU049,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21,Male,15.0,88%,82,Yes,No,Good

In [23]:
df['Gender']= df['Gender'].str.strip()
df['Gender']=df['Gender'].str.capitalize()
df['Gender'].unique()

<StringArray>
['Male', 'Female', 'M', 'F']
Length: 4, dtype: str

In [26]:
df['Gender']=df['Gender'].replace({"M":"Male"})
df['Gender'].value_counts()

Gender
Male      27
Female    20
F          3
Name: count, dtype: int64

In [28]:
df['Gender']= df['Gender'].replace(['M', 'F'], ['Male', 'Female'])
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
1,STU002,Jane Wanjiku,21,Female,22.0,91%,81,Yes,No,Excellent
2,STU003,Peter Kamau,19,Male,10.0,78%,65,YES,No,Average
3,STU004,mary njeri,22,Female,18.0,88%,74,Yes,YES,Good
4,STU005,David Ochieng,20,Male,25.0,95%,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20,Female,NaN,82%,68,No,Yes,Average
6,STU007,Brian Otieno,21,Male,30.0,110%,92,Yes,No,Excellent
7,STU008,Susan Wambui,19,Female,8.0,75%,54,No,No,poor
8,STU009,Kevin Kariuki,23,Male,12.0,80%,61,yes,No,Average
9,STU010,Ann Nyambura,20,Female,20.0,87%,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21,Male,-5.0,89%,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22,Female,16.0,NaN,84,Yes,No,Excellent
12,STU013,James Maina,19,Male,14.0,83%,59,No,Yes,Average
13,STU014,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
14,STU015,Michael Kibet,25,Male,40.0,97%,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19,Female,11.0,76%,62,NO,No,Average
16,STU017,Daniel Mutua,21,Male,NaN,84%,71,Yes,No,Good
17,STU018,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
18,STU019,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
19,STU020,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
20,STU021,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
21,STU022,Peter Kamau,19,Male,10.0,78%,65,YES,No,Average
22,STU023,Rose Njeri,20,Female,18.0,88%,74,Yes,No,Good
23,STU024,Joseph Kariuki,21,Male,100.0,90%,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20,Female,23.0,105%,91,Yes,No,Excellent
25,STU026,NaN,22,Male,16.0,86%,73,Yes,No,Good
26,STU027,Patrick Ouma,19,Male,9.0,79%,60,No,Yes,Average
27,STU028,Sarah Chebet,21,Female,18.0,88%,77,Yes,No,Good
28,STU029,Mark Otieno,20,Male,15.0,82%,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19,Female,12.0,74%,58,No,No,Poor
30,STU031,Victor Maina,20,Male,20.0,90%,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21,Female,24.0,93%,87,Yes,No,Excellent
32,STU033,George Mutua,22,Male,17.0,85%,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20,Female,14.0,80%,64,No,No,Average
34,STU035,Robert Kiptoo,19,Male,16.0,83%,70,Yes,No,Good
35,STU036,Naomi Chebet,21,Female,19.0,91%,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20,Male,13.0,78%,63,No,Yes,Average
37,STU038,Mercy Auma,19,Female,10.0,72%,51,No,Yes,poor
38,STU039,David Kamau,21,Male,18.0,86%,78,Yes,No,Good
39,STU040,Jane Wambui,20,Female,21.0,94%,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23,Male,12.0,80%,61,yes,No,Average
41,STU042,Brian Otieno,21,Male,30.0,89%,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19,Female,11.0,76%,62,NO,No,Average
43,STU044,Daniel Mutua,21,Male,17.0,84%,71,Yes,No,Good
44,STU045,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
45,STU046,Michael Kibet,25,Male,40.0,97%,95,Yes,No,Excellent
46,STU047,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
47,STU048,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
48,STU049,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21,Male,15.0,88%,82,Yes,No,Good

In [30]:
df.loc[df['Study_Hours'] > 24,'Study_Hours']=4.0
df['Study_Hours']= df['Study_Hours'].fillna(3.0)
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
1,STU002,Jane Wanjiku,21,Female,22.0,91%,81,Yes,No,Excellent
2,STU003,Peter Kamau,19,Male,10.0,78%,65,YES,No,Average
3,STU004,mary njeri,22,Female,18.0,88%,74,Yes,YES,Good
4,STU005,David Ochieng,20,Male,4.0,95%,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20,Female,3.0,82%,68,No,Yes,Average
6,STU007,Brian Otieno,21,Male,4.0,110%,92,Yes,No,Excellent
7,STU008,Susan Wambui,19,Female,8.0,75%,54,No,No,poor
8,STU009,Kevin Kariuki,23,Male,12.0,80%,61,yes,No,Average
9,STU010,Ann Nyambura,20,Female,20.0,87%,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21,Male,-5.0,89%,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22,Female,16.0,NaN,84,Yes,No,Excellent
12,STU013,James Maina,19,Male,14.0,83%,59,No,Yes,Average
13,STU014,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
14,STU015,Michael Kibet,25,Male,4.0,97%,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19,Female,11.0,76%,62,NO,No,Average
16,STU017,Daniel Mutua,21,Male,3.0,84%,71,Yes,No,Good
17,STU018,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
18,STU019,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
19,STU020,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
20,STU021,John Mwangi,20,Male,15.0,85%,72,Yes,No,Good
21,STU022,Peter Kamau,19,Male,10.0,78%,65,YES,No,Average
22,STU023,Rose Njeri,20,Female,18.0,88%,74,Yes,No,Good
23,STU024,Joseph Kariuki,21,Male,4.0,90%,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20,Female,23.0,105%,91,Yes,No,Excellent
25,STU026,NaN,22,Male,16.0,86%,73,Yes,No,Good
26,STU027,Patrick Ouma,19,Male,9.0,79%,60,No,Yes,Average
27,STU028,Sarah Chebet,21,Female,18.0,88%,77,Yes,No,Good
28,STU029,Mark Otieno,20,Male,15.0,82%,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19,Female,12.0,74%,58,No,No,Poor
30,STU031,Victor Maina,20,Male,20.0,90%,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21,Female,24.0,93%,87,Yes,No,Excellent
32,STU033,George Mutua,22,Male,17.0,85%,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20,Female,14.0,80%,64,No,No,Average
34,STU035,Robert Kiptoo,19,Male,16.0,83%,70,Yes,No,Good
35,STU036,Naomi Chebet,21,Female,19.0,91%,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20,Male,13.0,78%,63,No,Yes,Average
37,STU038,Mercy Auma,19,Female,10.0,72%,51,No,Yes,poor
38,STU039,David Kamau,21,Male,18.0,86%,78,Yes,No,Good
39,STU040,Jane Wambui,20,Female,21.0,94%,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23,Male,12.0,80%,61,yes,No,Average
41,STU042,Brian Otieno,21,Male,4.0,89%,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19,Female,11.0,76%,62,NO,No,Average
43,STU044,Daniel Mutua,21,Male,17.0,84%,71,Yes,No,Good
44,STU045,Faith Wairimu,20,Female,21.0,92%,88,Yes,No,Excellent
45,STU046,Michael Kibet,25,Male,4.0,97%,95,Yes,No,Excellent
46,STU047,Carol Wambui,20,Female,19.0,89%,79,Yes,Yes,Good
47,STU048,Eric Omondi,22,Male,17.0,81%,67,Yes,No,average
48,STU049,Beatrice Auma,19,Female,13.0,73%,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21,Male,15.0,88%,82,Yes,No,Good

In [31]:
df['Attendance']= df['Attendance'].str.replace('%', '')
df['Attendance']= df['Attendance'].astype(float)
df.loc[df['Attendance'] > 100, 'Attendance'] = 100.0
df['Attendance'] = df['Attendance'].fillna(85.0)
df

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Previous_Score,Internet_Access,Part_Time_Job,Performance
0,STU001,John Mwangi,20,Male,15.0,85.0,72,Yes,No,Good
1,STU002,Jane Wanjiku,21,Female,22.0,91.0,81,Yes,No,Excellent
2,STU003,Peter Kamau,19,Male,10.0,78.0,65,YES,No,Average
3,STU004,mary njeri,22,Female,18.0,88.0,74,Yes,YES,Good
4,STU005,David Ochieng,20,Male,4.0,95.0,89,Yes,No,Excellent
5,STU006,Grace Akinyi,20,Female,3.0,82.0,68,No,Yes,Average
6,STU007,Brian Otieno,21,Male,4.0,100.0,92,Yes,No,Excellent
7,STU008,Susan Wambui,19,Female,8.0,75.0,54,No,No,poor
8,STU009,Kevin Kariuki,23,Male,12.0,80.0,61,yes,No,Average
9,STU010,Ann Nyambura,20,Female,20.0,87.0,76,Yes,No,Good
10,STU011,Samuel Kiptoo,21,Male,-5.0,89.0,70,Yes,Yes,Good
11,STU012,Lilian Chebet,22,Female,16.0,85.0,84,Yes,No,Excellent
12,STU013,James Maina,19,Male,14.0,83.0,59,No,Yes,Average
13,STU014,Faith Wairimu,20,Female,21.0,92.0,88,Yes,No,Excellent
14,STU015,Michael Kibet,25,Male,4.0,97.0,95,Yes,No,Excellent
15,STU016,Lucy Atieno,19,Female,11.0,76.0,62,NO,No,Average
16,STU017,Daniel Mutua,21,Male,3.0,84.0,71,Yes,No,Good
17,STU018,Carol Wambui,20,Female,19.0,89.0,79,Yes,Yes,Good
18,STU019,Eric Omondi,22,Male,17.0,81.0,67,Yes,No,average
19,STU020,Beatrice Auma,19,Female,13.0,73.0,55,No,Yes,Poor
20,STU021,John Mwangi,20,Male,15.0,85.0,72,Yes,No,Good
21,STU022,Peter Kamau,19,Male,10.0,78.0,65,YES,No,Average
22,STU023,Rose Njeri,20,Female,18.0,88.0,74,Yes,No,Good
23,STU024,Joseph Kariuki,21,Male,4.0,90.0,82,Yes,No,Excellent
24,STU025,Agnes Wanjiku,20,Female,23.0,100.0,91,Yes,No,Excellent
25,STU026,NaN,22,Male,16.0,86.0,73,Yes,No,Good
26,STU027,Patrick Ouma,19,Male,9.0,79.0,60,No,Yes,Average
27,STU028,Sarah Chebet,21,Female,18.0,88.0,77,Yes,No,Good
28,STU029,Mark Otieno,20,Male,15.0,82.0,69,Yes,NaN,Average
29,STU030,Alice Wanjiru,19,Female,12.0,74.0,58,No,No,Poor
30,STU031,Victor Maina,20,Male,20.0,90.0,80,Yes,No,Good
31,STU032,Elizabeth Akinyi,21,Female,24.0,93.0,87,Yes,No,Excellent
32,STU033,George Mutua,22,Male,17.0,85.0,75,Yes,Yes,Good
33,STU034,Christine Wairimu,20,Female,14.0,80.0,64,No,No,Average
34,STU035,Robert Kiptoo,19,Male,16.0,83.0,70,Yes,No,Good
35,STU036,Naomi Chebet,21,Female,19.0,91.0,85,Yes,No,Excellent
36,STU037,Samuel Ochieng,20,Male,13.0,78.0,63,No,Yes,Average
37,STU038,Mercy Auma,19,Female,10.0,72.0,51,No,Yes,poor
38,STU039,David Kamau,21,Male,18.0,86.0,78,Yes,No,Good
39,STU040,Jane Wambui,20,Female,21.0,94.0,90,Yes,No,Excellent
40,STU041,Kevin Kariuki,23,Male,12.0,80.0,61,yes,No,Average
41,STU042,Brian Otieno,21,Male,4.0,89.0,92,Yes,No,Excellent
42,STU043,Lucy Atieno,19,Female,11.0,76.0,62,NO,No,Average
43,STU044,Daniel Mutua,21,Male,17.0,84.0,71,Yes,No,Good
44,STU045,Faith Wairimu,20,Female,21.0,92.0,88,Yes,No,Excellent
45,STU046,Michael Kibet,25,Male,4.0,97.0,95,Yes,No,Excellent
46,STU047,Carol Wambui,20,Female,19.0,89.0,79,Yes,Yes,Good
47,STU048,Eric Omondi,22,Male,17.0,81.0,67,Yes,No,average
48,STU049,Beatrice Auma,19,Female,13.0,73.0,55,No,Yes,Poor
49,STU050,Joseph Kariuki,21,Male,15.0,88.0,82,Yes,No,Good